/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author palakagrawal
 */
public class mainJframe extends javax.swing.JFrame {

    /**
     * Creates new form mainJframe
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public mainJframe() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        ImageIcon img = new ImageIcon(getClass().getResource("/images/logo.png"));
         logoLbl.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        loginPane = new javax.swing.JPanel();
        signInTitleLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        signUpLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        signInBtn = new javax.swing.JButton();
        containerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(10);

        loginPane.setBackground(new java.awt.Color(255, 255, 255));
        loginPane.setPreferredSize(new java.awt.Dimension(415, 512));
        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInTitleLabel.setFont(new java.awt.Font("Bradley Hand", 1, 24)); // NOI18N
        signInTitleLabel.setText("Sign In");
        loginPane.add(signInTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 105, -1));

        userNameLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        userNameLabel.setText("UserName:");
        loginPane.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 104, -1));
        loginPane.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 187, 39));

        passwordLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        passwordLabel.setText("Password:");
        loginPane.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 104, -1));
        loginPane.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 187, 40));

        signUpLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        signUpLabel.setText("Not a part yet? ");
        loginPane.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 130, 35));

        logOutButton.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign_out.jpg"))); // NOI18N
        logOutButton.setBorder(null);
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        loginPane.add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 80, 80));

        titleLabel.setFont(new java.awt.Font("Bradley Hand", 1, 26)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 51, 51));
        titleLabel.setText("BeingHuman System");
        loginPane.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        messageLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        messageLabel.setText("The Charitable Journey...");
        loginPane.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        signUpBtn.setBackground(new java.awt.Color(255, 255, 255));
        signUpBtn.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        signUpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signUp.jpeg"))); // NOI18N
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        loginPane.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 110, 40));
        loginPane.add(logoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 110));

        signInBtn.setBackground(new java.awt.Color(255, 255, 255));
        signInBtn.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        signInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign.jpeg"))); // NOI18N
        signInBtn.setBorder(null);
        signInBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign.jpeg"))); // NOI18N
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        loginPane.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 100, 44));

        jSplitPane1.setLeftComponent(loginPane);

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));
        containerPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(containerPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        signInBtn.setEnabled(true);
        signUpBtn.setEnabled(true);
        userNameTextField.setText("");
        passwordTextField.setText("");
        userNameTextField.setEnabled(true);
        passwordTextField.setEnabled(true);
        
        logOutButton.setEnabled(false);
        containerPanel.removeAll();
        JPanel blankJP = new JPanel();
        containerPanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) containerPanel.getLayout();
        crdLyt.next(containerPanel);
        dB4OUtil.storeSystem(system);
        
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        signUpBtn.setEnabled(false);
        logOutButton.setVisible(false);
        
        SignUpJPanel signUpPane = new SignUpJPanel(containerPanel, system, dB4OUtil);
        containerPanel.add("SignUpJPanel", signUpPane);
        CardLayout layout = (CardLayout) containerPanel.getLayout();
        layout.next(containerPanel);
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        // TODO add your handling code here:
        // Get user name
        String userName = userNameTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordTextField.getPassword();
        String password = String.valueOf(passwordCharArray);

        String generatedPassword = null;
        try {
            // Create MessageDigest instance for MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
            //Add password bytes to digest
            md.update(password.getBytes());
            //Get the hash's bytes
            byte[] bytes = md.digest();
            //This bytes[] has bytes in decimal format;
            //Convert it to hexadecimal format
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            //Get complete hashed password in hex format
            generatedPassword = sb.toString();
            System.out.println("encrypted logeed in "+generatedPassword+"pwd "+password);
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }

        //Step 1: check system admin user account directory
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, generatedPassword);
        Enterprise isEnterprise = null;
        Organization isOrganization = null;
        if (userAccount == null) {
            //Step 2: Go inside network and check each enterprise
            for (Network network : system.getNetworkList()) {
                //Step 2a: check against each enterprise
                for (Enterprise enterprise : network.getEnterpriseList().getEnterpriseList()) {
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, generatedPassword);

                    if (userAccount == null) {
                        //Step 3: check each organization
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {

                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, generatedPassword);
                            if (userAccount != null) {
                                isEnterprise = enterprise;
                                isOrganization = organization;
                                break;
                            }
                        }
                    }
                    else{
                        isEnterprise = enterprise;
                        break;
                    }
                    if(isOrganization != null){
                        break;
                    }

                }
                if(isEnterprise != null){
                    break;
                }

            }
        }
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Invalid Credential");
            return;
        }
        else{
            CardLayout layout = (CardLayout) containerPanel.getLayout();
            containerPanel.add("workArea", userAccount.getRole().createWorkArea(containerPanel, userAccount, isOrganization, isEnterprise, system));
            layout.next(containerPanel);
        }

        signInBtn.setEnabled(false);
        signUpBtn.setEnabled(false);
        logOutButton.setVisible(true);
        logOutButton.setEnabled(true);
        userNameTextField.setEnabled(false);
        passwordTextField.setEnabled(false);

        JOptionPane.showMessageDialog(null, "Logged In successfully","Information",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_signInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel loginPane;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton signInBtn;
    private javax.swing.JLabel signInTitleLabel;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
