/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminWorkArea;

import Business.Chart.PieChart;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Panchi
 */
public class ViewReport extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ViewReport
     */
    public ViewReport(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionBtnGrp = new javax.swing.ButtonGroup();
        backJButton2 = new javax.swing.JButton();
        question1RadioBtn = new javax.swing.JRadioButton();
        question5RadioBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton2.setBackground(new java.awt.Color(255, 102, 102));
        backJButton2.setFont(new java.awt.Font("Bradley Hand", 1, 14)); // NOI18N
        backJButton2.setText("Cancel");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });
        add(backJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 120, 43));

        question1RadioBtn.setBackground(new java.awt.Color(255, 102, 102));
        questionBtnGrp.add(question1RadioBtn);
        question1RadioBtn.setFont(new java.awt.Font("Bradley Hand", 1, 14)); // NOI18N
        question1RadioBtn.setText("Number of Employee in each Organization");
        question1RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1RadioBtnActionPerformed(evt);
            }
        });
        add(question1RadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 59, -1, -1));

        question5RadioBtn.setBackground(new java.awt.Color(255, 102, 102));
        questionBtnGrp.add(question5RadioBtn);
        question5RadioBtn.setFont(new java.awt.Font("Bradley Hand", 1, 14)); // NOI18N
        question5RadioBtn.setText("Number of Organization in each Enterprise and Network");
        question5RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question5RadioBtnActionPerformed(evt);
            }
        });
        add(question5RadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 24)); // NOI18N
        jLabel1.setText("Select any option to view analytics");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void question5RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question5RadioBtnActionPerformed
        // TODO add your handling code here:
        if (question5RadioBtn.isSelected()) {
            PieChart demo = new PieChart("Pie Chart", "BeingHuman Statistics", userProcessContainer, system);
            demo.pack();
            RefineryUtilities.centerFrameOnScreen(demo);
            demo.setVisible(true);
        }
    }//GEN-LAST:event_question5RadioBtnActionPerformed

    private void question1RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1RadioBtnActionPerformed
        // TODO add your handling code here:
        if (question1RadioBtn.isSelected()) {
            PieChart demo = new PieChart("Pie Chart", "BeingHuman Statistics", userProcessContainer, system,1);
            demo.pack();
            RefineryUtilities.centerFrameOnScreen(demo);
            demo.setVisible(true);
        }
    }//GEN-LAST:event_question1RadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton question1RadioBtn;
    private javax.swing.JRadioButton question5RadioBtn;
    private javax.swing.ButtonGroup questionBtnGrp;
    // End of variables declaration//GEN-END:variables
}
