/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.LabAssistant;

import Business.Person.VitalSigns;
import javax.swing.JPanel;


/**
 *
 * @author Panchi
 */
public class VitalSignsGenerateJPanel extends javax.swing.JPanel {
    
    JPanel vitalSignPane;
    VitalSigns vs;
    
    /**
     * Creates new form VitalHistory
     */
    public VitalSignsGenerateJPanel(JPanel vitalSignPanel, VitalSigns vs) {
         initComponents();
         this.vs = vs;
         this.vitalSignPane = vitalSignPanel;
         populateVitalSigns();
    }
    public void populateVitalSigns(){
        ageLabel1.setText(String.valueOf(vs.getAge()));
        intervalLabel1.setText(String.valueOf(vs.getDonationInterval()));
        weightLabel1.setText(String.valueOf(vs.getWeight()));
        heightLabel1.setText(String.valueOf(vs.getHeight()));
        bloodPressureLabel1.setText(vs.getBloodpressure());
        diabeticLabel1.setText(vs.getDiabetic());
        hivLabel1.setText(vs.getHivAids());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vitalSignsDisplayPane = new javax.swing.JPanel();
        vitalLbl = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        intervalLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        hivLabel = new javax.swing.JLabel();
        bloodPressureLabel = new javax.swing.JLabel();
        diabeticLabel = new javax.swing.JLabel();
        ageLabel1 = new javax.swing.JLabel();
        intervalLabel1 = new javax.swing.JLabel();
        weightLabel1 = new javax.swing.JLabel();
        heightLabel1 = new javax.swing.JLabel();
        bloodPressureLabel1 = new javax.swing.JLabel();
        diabeticLabel1 = new javax.swing.JLabel();
        hivLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        vitalSignsDisplayPane.setBackground(new java.awt.Color(255, 255, 255));

        vitalLbl.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        vitalLbl.setForeground(new java.awt.Color(255, 51, 51));
        vitalLbl.setText("Vital History");

        ageLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        ageLabel.setText("Age:");

        intervalLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        intervalLabel.setText("Last Donation Interval:");

        heightLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        heightLabel.setText("Height:");

        weightLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        weightLabel.setText("Weight:");

        hivLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        hivLabel.setText("HIV/Aids:");

        bloodPressureLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        bloodPressureLabel.setText("BloodPressure:");

        diabeticLabel.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        diabeticLabel.setText("Diabetic:");

        ageLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N
        ageLabel1.setToolTipText("");

        intervalLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N

        weightLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N

        heightLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N

        bloodPressureLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N

        diabeticLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N

        hivLabel1.setFont(new java.awt.Font("Bradley Hand", 1, 18)); // NOI18N

        javax.swing.GroupLayout vitalSignsDisplayPaneLayout = new javax.swing.GroupLayout(vitalSignsDisplayPane);
        vitalSignsDisplayPane.setLayout(vitalSignsDisplayPaneLayout);
        vitalSignsDisplayPaneLayout.setHorizontalGroup(
            vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalSignsDisplayPaneLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vitalSignsDisplayPaneLayout.createSequentialGroup()
                        .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intervalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodPressureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diabeticLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hivLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intervalLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(weightLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(heightLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bloodPressureLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diabeticLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hivLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vitalSignsDisplayPaneLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(vitalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        vitalSignsDisplayPaneLayout.setVerticalGroup(
            vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalSignsDisplayPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(vitalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intervalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intervalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weightLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heightLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bloodPressureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloodPressureLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diabeticLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diabeticLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(vitalSignsDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hivLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hivLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(vitalSignsDisplayPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JLabel bloodPressureLabel1;
    private javax.swing.JLabel diabeticLabel;
    private javax.swing.JLabel diabeticLabel1;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel heightLabel1;
    private javax.swing.JLabel hivLabel;
    private javax.swing.JLabel hivLabel1;
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JLabel intervalLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vitalLbl;
    private javax.swing.JPanel vitalSignsDisplayPane;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightLabel1;
    // End of variables declaration//GEN-END:variables
}
